version: "{build}"
clone_depth: 5
build: off

environment:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  matrix:
    - RUBY_FOLDER_VER: "26"
    - RUBY_FOLDER_VER: "24"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%-x64\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/test

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml, Gemfile, jekyll-feed.gemspec'
